### ISSUE TITLE
Build Failed in iOS using OutSystems 

### ISSUE THREAD

**Issue by bassam-basamad-bupa** [HaylLtd/cordova-plugin-background-geolocation#117]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build] duplicate symbol '_OBJC_METACLASS_$_DDLogMessage' in:
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDLog.o)
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build] duplicate symbol '_OBJC_CLASS_$_DDLoggerNode' in:
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDLog.o)
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build] duplicate symbol '_OBJC_METACLASS_$_DDLoggerNode' in:
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDLog.o)
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDLogMessage._threadID' in:
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDLog.o)
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._colorProfilesArray' in:
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.fgCodeIndex' in:
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.bgCodeIndex' in:
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.fgCodeRaw' in:
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.bgCodeRaw' in:
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.context' in:
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.185Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._colorProfilesDict' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._automaticallyAppendNewlineForCustomFormatters' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._calendarUnitFlags' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_CLASS_$_DDTTYLogger' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_METACLASS_$_DDTTYLogger' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.fg_r' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.bg_r' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._app' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._appLen' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.resetCodeLen' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.fgCodeLen' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.bgCodeLen' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._pidLen' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.mask' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.fg_g' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.bg_g' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._appName' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_CLASS_$_DDTTYLoggerColorProfile' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_METACLASS_$_DDTTYLoggerColorProfile' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.resetCode' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.fgCode' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.bgCode' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._pid' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._colorsEnabled' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.fg_b' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLoggerColorProfile.bg_b' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] duplicate symbol '_OBJC_IVAR_$_DDTTYLogger._processID' in:
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/IntermediateBuildFilesPath/TestAppVideo.build/Release-iphoneos/TestAppVideo.build/Objects-normal/arm64/CocoaLumberjack.o
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build]     source/platforms/ios/build/device/libCocoaLumberjack.a(DDTTYLogger.o)
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] ld: 117 duplicate symbols for architecture arm64
[2022-09-01T14:02:50.186Z] [VERBOSE] [Build] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[2022-09-01T14:02:50.233Z] [VERBOSE] [Build] source/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'FLEX' from project 'Pods')
[2022-09-01T14:02:50.233Z] [VERBOSE] [Build] source/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'CocoaLumberjack' from project 'Pods')
[2022-09-01T14:02:50.233Z] [VERBOSE] [Build] source/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'YapDatabase' from project 'Pods')
[2022-09-01T14:02:50.246Z] [VERBOSE] [Build] ** ARCHIVE FAILED **
[2022-09-01T14:02:50.246Z] [VERBOSE] [Build] The following build commands failed:
[2022-09-01T14:02:50.246Z] [VERBOSE] [Build] 	Ld /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/InstallationBuildProductsLocation/Applications/TestAppVideo.app/TestAppVideo normal (in target 'TestAppVideo' from project 'TestAppVideo')
[2022-09-01T14:02:50.246Z] [VERBOSE] [Build] (1 failure)
[2022-09-01T14:02:50.250Z] [VERBOSE] [Build] Command finished with error code 65: xcodebuild -workspace,TestAppVideo.xcworkspace,-scheme,TestAppVideo,-configuration,Release,-destination,generic/platform=iOS,-archivePath,TestAppVideo.xcarchive,archive,CONFIGURATION_BUILD_DIR=source/platforms/ios/build/device,SHARED_PRECOMPS_DIR=source/platforms/ios/build/sharedpch,OTHER_CODE_SIGN_FLAGS=--options runtime --keychain keys/keychain.keychain-db
[2022-09-01T14:02:50.251Z] [VERBOSE] [Build] xcodebuild: Command failed with exit code 65
[2022-09-01T14:02:50.251Z] [VERBOSE] [Build] Error: xcodebuild: Command failed with exit code 65
[2022-09-01T14:02:50.251Z] [VERBOSE] [Build]     at ChildProcess.whenDone (source/node_modules/cordova-common/src/superspawn.js:136:25)
[2022-09-01T14:02:50.252Z] [VERBOSE] [Build]     at ChildProcess.emit (events.js:400:28)
[2022-09-01T14:02:50.252Z] [VERBOSE] [Build]     at maybeClose (internal/child_process.js:1088:16)
[2022-09-01T14:02:50.252Z] [VERBOSE] [Build]     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
[2022-09-01T14:02:51.857Z] [INFO] [Build] Zipping application source code...
[2022-09-01T14:02:58.062Z] [INFO] [Build] Saving package and source files...
[2022-09-01T14:02:58.062Z] [ERROR] [Build] -- v --
[2022-09-01T14:02:58.062Z] [ERROR] [Build] The build phase failed to complete!
[2022-09-01T14:02:58.063Z] [ERROR] [Build] Reason: Couldn't generate your app. If the problem persists, check our documentation for more information.
[2022-09-01T14:02:58.063Z] [ERROR] [Build] Additional information:
[2022-09-01T14:02:58.063Z] [ERROR] [Build] 2022-09-01 14:02:11.942 xcodebuild[78351:220790089] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[2022-09-01T14:02:58.063Z] [ERROR] [Build] 2022-09-01 14:02:11.942 xcodebuild[78351:220790089] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[2022-09-01T14:02:58.063Z] [ERROR] [Build] 2022-09-01 14:02:11.982 xcodebuild[78351:220790089] XType: com.apple.fonts is not accessible.
[2022-09-01T14:02:58.063Z] [ERROR] [Build] 2022-09-01 14:02:11.982 xcodebuild[78351:220790089] XType: XTFontStaticRegistry is enabled.
[2022-09-01T14:02:58.063Z] [ERROR] [Build] ** ARCHIVE FAILED **
[2022-09-01T14:02:58.063Z] [ERROR] [Build] The following build commands failed:
[2022-09-01T14:02:58.063Z] [ERROR] [Build] 	Ld /Users/sandbox02/Library/Developer/Xcode/DerivedData/TestAppVideo-hforquemvcbheaaubkgcqqyozlee/Build/Intermediates.noindex/ArchiveIntermediates/TestAppVideo/InstallationBuildProductsLocation/Applications/TestAppVideo.app/TestAppVideo normal (in target 'TestAppVideo' from project 'TestAppVideo')
[2022-09-01T14:02:58.063Z] [ERROR] [Build] (1 failure)
[2022-09-01T14:02:58.063Z] [ERROR] [Build] xcodebuild: Command failed with exit code 65
[2022-09-01T14:02:58.063Z] [ERROR] [Build] -- ^ --
[2022-09-01T14:02:58.063Z] [INFO] [Build] Application was not successfully generated!
[2022-09-01T14:03:02.490Z] [INFO] [Build] Execution time: 202981 ms

**Comment by HarelM** [comment]
I don't know what outsystem is.
Also the template is here for a reason, it is best to fill out of you want help...

**Comment by bassam-basamad-bupa** [comment]
added some of the logs ..
Out Systems:
https://success.outsystems.com/Support/Release_Notes/Mobile_Apps_Build_Service_Versions

**Comment by HarelM** [comment]
This is not with this plugin, sorry, I'm not familiar with this system. Good luck!
