### ISSUE TITLE
Error start service

### ISSUE THREAD

**Issue by josuelmm** [HaylLtd/cordova-plugin-background-geolocation#118]
2022-09-05 02:08:31.943 19241-19241/site.seelight.caminando E/AndroidRuntime: FATAL EXCEPTION: main
    Process: site.seelight.caminando, PID: 19241
    java.lang.RuntimeException: Unable to create service com.marianhello.bgloc.service.LocationServiceImpl: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4648)
        at android.app.ActivityThread.access$1800(ActivityThread.java:276)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2149)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8261)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:463)
        at android.content.res.MiuiResources.getText(MiuiResources.java:106)
        at android.content.res.Resources.getString(Resources.java:556)
        at android.content.Context.getString(Context.java:715)
        at com.marianhello.bgloc.ResourceResolver.getString(ResourceResolver.java:37)
        at com.marianhello.bgloc.ResourceResolver.getAccountName(ResourceResolver.java:41)
        at com.marianhello.bgloc.service.LocationServiceImpl.onCreate(LocationServiceImpl.java:192)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4635)
        at android.app.ActivityThread.access$1800(ActivityThread.java:276) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2149) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8261) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
2022-09-05 02:08:31.947 19241-19241/site.seelight.caminando E/com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: mainjava.lang.RuntimeException: Unable to create service com.marianhello.bgloc.service.LocationServiceImpl: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4648)
        at android.app.ActivityThread.access$1800(ActivityThread.java:276)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2149)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8261)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:463)
        at android.content.res.MiuiResources.getText(MiuiResources.java:106)
        at android.content.res.Resources.getString(Resources.java:556)
        at android.content.Context.getString(Context.java:715)
        at com.marianhello.bgloc.ResourceResolver.getString(ResourceResolver.java:37)
        at com.marianhello.bgloc.ResourceResolver.getAccountName(ResourceResolver.java:41)
        at com.marianhello.bgloc.service.LocationServiceImpl.onCreate(LocationServiceImpl.java:192)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4635)
    	... 9 common frames omitted
2022-09-05 02:12:21.933 19508-19508/site.seelight.caminando E/eb.riberacamin: Invalid ID 0x00000000.
2022-09-05 02:12:22.004 19508-19508/site.seelight.caminando E/eb.riberacamin: Invalid ID 0x00000000.
2022-09-05 02:12:22.004 19508-19508/site.seelight.caminando E/eb.riberacamin: Invalid ID 0x00000000.
2022-09-05 02:12:31.681 19508-19508/site.seelight.caminando E/eb.riberacamin: Invalid ID 0x00000000.
2022-09-05 02:12:31.682 19508-19508/site.seelight.caminando E/AndroidRuntime: FATAL EXCEPTION: main
    Process: site.seelight.caminando, PID: 19508
    java.lang.RuntimeException: Unable to create service com.marianhello.bgloc.service.LocationServiceImpl: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4648)
        at android.app.ActivityThread.access$1800(ActivityThread.java:276)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2149)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8261)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:463)
        at android.content.res.MiuiResources.getText(MiuiResources.java:106)
        at android.content.res.Resources.getString(Resources.java:556)
        at android.content.Context.getString(Context.java:715)
        at com.marianhello.bgloc.ResourceResolver.getString(ResourceResolver.java:37)
        at com.marianhello.bgloc.ResourceResolver.getAccountName(ResourceResolver.java:41)
        at com.marianhello.bgloc.service.LocationServiceImpl.onCreate(LocationServiceImpl.java:192)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4635)
        at android.app.ActivityThread.access$1800(ActivityThread.java:276) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2149) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8261) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
2022-09-05 02:12:31.686 19508-19508/site.seelight.caminando E/com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: mainjava.lang.RuntimeException: Unable to create service com.marianhello.bgloc.service.LocationServiceImpl: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4648)
        at android.app.ActivityThread.access$1800(ActivityThread.java:276)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2149)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8261)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:463)
        at android.content.res.MiuiResources.getText(MiuiResources.java:106)
        at android.content.res.Resources.getString(Resources.java:556)
        at android.content.Context.getString(Context.java:715)
        at com.marianhello.bgloc.ResourceResolver.getString(ResourceResolver.java:37)
        at com.marianhello.bgloc.ResourceResolver.getAccountName(ResourceResolver.java:41)
        at com.marianhello.bgloc.service.LocationServiceImpl.onCreate(LocationServiceImpl.java:192)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4635)
    	... 9 common frames omitted

**Comment by HarelM** [comment]
Seems like you have a missing resource somewhere:
`android.content.res.Resources$NotFoundException: String resource ID`
I would advise to try and debug this in android studio to see where it fails and what resource is missing...
